CREATE TABLE users (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
username TINYTEXT NOT NULL,
email TINYTEXT NOT NULL,
confirm_string TINYTEXT NOT NULL,
confirmed TINYINT DEFAULT 0,
PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;